### ISSUE TITLE
Feature: Adding a static library 

### ISSUE THREAD

**Issue by JonnycatMeow** [mumble-voip/libcrossaudio#1]
i compiled for macOS and i got a dylib and i was wondering if you could add a feature that instead of building dynamic you could also do static

**Comment by davidebeatrici** [comment]
Added in 68f92ea3c0b86f66b0f73a6b8c4202d155723f46.

Please note that there is no support for CoreAudio yet.

**Comment by JonnycatMeow** [comment]
ok thank you

**Comment by JonnycatMeow** [comment]
so what do i have to do to enable the static library version? do i have to do cmake CROSSAUDIO_STATIC to enable it?

**Comment by davidebeatrici** [comment]
`cmake -DCROSSAUDIO_STATIC=ON`

**Comment by JonnycatMeow** [comment]
thank you also do you want me to send the binaries?

**Comment by JonnycatMeow** [comment]
ok it works

**Comment by JonnycatMeow** [comment]
[Mac.zip](https://github.com/mumble-voip/libcrossaudio/files/10367352/Mac.zip)
here are the binaries

**Comment by davidebeatrici** [comment]
Okay.
